The following code helps you to load and visualize the data (skeleton) in 3D xyz coordinates.
 

In [38]:
import numpy as np
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import os
plt.style.use('seaborn-poster')

#filename and folder to plot
fname= "jumping_1"
folder = "hw2data/train/"

vals = np.load(folder+fname+".npy")
xyz = np.reshape(vals[:,:], (38,3,-1))


print(xyz.shape)

#define the root joint and scaling of the values
r = 1000
xroot, yroot, zroot = xyz[0,0,0], xyz[0,0,1], xyz[0,0,2]

#define the connections between the joints (skeleton) 
I = np.array(
        [1, 2, 3, 4, 5, 6, 1, 8, 9, 10, 11, 12, 1, 14, 15, 16, 17, 18, 19, 16, 21, 22, 23, 25, 26, 24, 28, 16, 30, 31,
         32, 33, 34, 35, 33, 37]) - 1
J = np.array(
        [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29, 30, 31, 32,
         33, 34, 35, 36, 37, 38]) - 1


(38, 3, 100)


C:\Users\samip\AppData\Local\Temp\ipykernel_22520\3749769116.py:6: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-poster')


In [42]:
print(xyz[:,:,0])
print(np.shape(vals))
print(vals[:,0])

[[ 2.56624800e-04 -1.10068824e-02 -2.22715306e+00]
 [ 2.56624800e-04 -1.10068824e-02 -2.22715306e+00]
 [-3.73661342e+01 -1.19306604e+02 -1.27545953e+02]
 [-3.99120114e+01 -1.21837703e+02 -6.59161850e+02]
 [-1.34763044e+02 -7.14346327e+01 -1.15804639e+03]
 [-3.74982028e+01 -1.88098562e+02 -1.19173302e+03]
 [ 1.36003080e+01 -2.46232143e+02 -1.18314047e+03]
 [ 2.56624800e-04 -1.10068824e-02 -2.22715306e+00]
 [ 1.02430923e+02  6.21491161e+01 -1.29485876e+02]
 [ 1.24984206e+02  3.21269857e+01 -6.59751674e+02]
 [ 7.42816417e+01  1.24097972e+02 -1.15369733e+03]
 [ 1.89987130e+02  2.77137019e+01 -1.19753925e+03]
 [ 2.48307015e+02 -2.37279618e+01 -1.19033599e+03]
 [ 5.44490787e-02 -5.30025255e-02 -2.25242547e+00]
 [-7.16934248e+00  5.76547308e-01  1.41725496e+02]
 [-1.21636203e+01 -2.59347257e+00  2.86163880e+02]
 [-1.21646349e+01 -2.61257099e+00  2.86153357e+02]
 [-3.23695119e+01 -1.86041247e+01  3.93293546e+02]
 [-3.40518543e+01 -2.49871027e+01  5.02661001e+02]
 [-1.66371808e+01 -2.94389670e+

In [5]:
# plot the skeleton accroding to joints (each plot is png image in anim folder)

for tind in range(1,xyz.shape[2]):
    
    fig = plt.figure(figsize = (10,10))
    ax = plt.axes(projection='3d')
    for ijind in range(0,I.shape[0]):
        xline = np.array([xyz[I[ijind],0,tind], xyz[J[ijind],0,tind]])
        yline = np.array([xyz[I[ijind],1,tind], xyz[J[ijind],1,tind]])
        zline = np.array([xyz[I[ijind],2,tind], xyz[J[ijind],2,tind]])
        # use plot if you'd like to plot skeleton with lines
        ax.plot(xline,yline,zline)
    
    # use scatter if you'd like to plot all points without lines 
    # ax.scatter(xyz[:,0,tind],xyz[:,1,tind],xyz[:,2,tind], c = 'r', s = 50)   

    ax.set_xlim([-r+xroot, r+xroot])
    ax.set_zlim([-r+zroot, r+zroot])
    ax.set_ylim([-r+yroot, r+yroot])
    
    plt.savefig('anim/'+f"{tind}.png")
    plt.close()

# when plotting a single sample (the skeleton can simply be plotted without saving an image)
#     plt.draw()
#     plt.pause(.001)
#     plt.show()

 
    
# save the animated plot as a gif in anim folder 
from PIL import Image

images = [Image.open('anim/'+f"{n}.png") for n in range(1,xyz.shape[2])]
images[0].save('anim/'+fname+'.gif', save_all=True, append_images=images[1:], duration=30, loop=0) 

# remove ploted png images
for n in range(1,xyz.shape[2]):
    os.remove('anim/'+f"{n}.png")





In [2]:
print(r)

1000


In [13]:
print(np.shape(xyz))

(38, 3, 100)


In [6]:
#Here is how to save a single image. The xyz variable is the data you need. It is a 38 by 3 array with the xyz coordinates it plots

for tind in range(1,2):
    
    fig = plt.figure(figsize = (10,10))
    ax = plt.axes(projection='3d')
    for ijind in range(0,I.shape[0]):
        xline = np.array([xyz[I[ijind],0,tind], xyz[J[ijind],0,tind]])
        yline = np.array([xyz[I[ijind],1,tind], xyz[J[ijind],1,tind]])
        zline = np.array([xyz[I[ijind],2,tind], xyz[J[ijind],2,tind]])
        # use plot if you'd like to plot skeleton with lines
        ax.plot(xline,yline,zline)
    
    # use scatter if you'd like to plot all points without lines 
    # ax.scatter(xyz[:,0,tind],xyz[:,1,tind],xyz[:,2,tind], c = 'r', s = 50)   

    ax.set_xlim([-r+xroot, r+xroot])
    ax.set_zlim([-r+zroot, r+zroot])
    ax.set_ylim([-r+yroot, r+yroot])
    
    plt.savefig('anim/'+f"{tind}.png")#where do you want to save the image
    plt.close()

Below, I will figure out how to plot the PC modes in the same way I make plots for the actual training data

In [46]:
import numpy as np
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
import os

# Load data and perform SVD
folder = "hw2data/train/"
file_list = os.listdir(folder)
numpy_files = [file for file in file_list if file.endswith('.npy')]

X_train = np.zeros((114, 1500))

for i in range(len(numpy_files)):
    path = os.path.join(folder, numpy_files[i])
    array = np.load(path)
    X_train[:, i*100:(i+1)*100] = array

# Center the data
mean_X_train = np.mean(X_train, axis=1)[:, None]
centered_x_train = X_train - mean_X_train

# Perform SVD
dU, ds, dVt = np.linalg.svd(centered_x_train, full_matrices=False)

# Define the number of principal component modes to visualize
num_pc_modes = 10

# Define the connections between the joints (skeleton) 
I = np.array(
    [1, 2, 3, 4, 5, 6, 1, 8, 9, 10, 11, 12, 1, 14, 15, 16, 17, 18, 19, 16, 21, 22, 23, 25, 26, 24, 28, 16, 30, 31,
     32, 33, 34, 35, 33, 37]) - 1
J = np.array(
    [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29, 30, 31, 32,
     33, 34, 35, 36, 37, 38]) - 1

# Define the root joint and scaling of the values
r = 1000

# Create the output folder if it doesn't exist
output_folder = 'pc_modes/'
os.makedirs(output_folder, exist_ok=True)

# Plot the principal components
for tind in range(num_pc_modes):
    # Scale the PC mode by the corresponding singular value
    pc_mode_scaled = dU[:, tind] * ds[tind]
    
    # Add the mean back to the scaled PC mode
    pc_mode_scaled += mean_X_train[:, 0]
    
    # Reshape the PC mode for visualization
    pc_mode_reshaped = pc_mode_scaled.reshape(38, 3)
    
    fig = plt.figure(figsize=(10, 10))
    ax = plt.axes(projection='3d')
    for ijind in range(I.shape[0]):
        xline = np.array([pc_mode_reshaped[I[ijind], 0], pc_mode_reshaped[J[ijind], 0]])
        yline = np.array([pc_mode_reshaped[I[ijind], 1], pc_mode_reshaped[J[ijind], 1]])
        zline = np.array([pc_mode_reshaped[I[ijind], 2], pc_mode_reshaped[J[ijind], 2]])
        ax.plot(xline, yline, zline)
    
    #ax.set_xlim([-r + np.mean(pc_mode_reshaped[:, 0]), r + np.mean(pc_mode_reshaped[:, 0])])
    #ax.set_zlim([-r + np.mean(pc_mode_reshaped[:, 2]), r + np.mean(pc_mode_reshaped[:, 2])])
    #ax.set_ylim([-r + np.mean(pc_mode_reshaped[:, 1]), r + np.mean(pc_mode_reshaped[:, 1])])

    plt.savefig(output_folder + f"pc_mode_{tind + 1}.png")
    plt.close()

In [44]:
#print(dU[:,0])
#print(dU[:,2])
print(mean_X_train)

[[ 3.61187491e-02]
 [ 2.91235308e-02]
 [-2.31329709e+00]
 [ 3.61187491e-02]
 [ 2.91235308e-02]
 [-2.31329709e+00]
 [-4.49510669e+01]
 [-1.08942784e+02]
 [-1.31291964e+02]
 [ 5.59935007e+01]
 [-1.81322169e+02]
 [-6.19973266e+02]
 [-6.97515161e+01]
 [-2.99960246e+01]
 [-1.04059198e+03]
 [ 7.46745249e+00]
 [-1.07539834e+02]
 [-1.10592978e+03]
 [ 5.15263760e+01]
 [-1.52283161e+02]
 [-1.11377513e+03]
 [ 3.61187491e-02]
 [ 2.91235308e-02]
 [-2.31329709e+00]
 [ 1.09258925e+02]
 [ 5.59863064e+01]
 [-1.24038437e+02]
 [ 1.97525089e+02]
 [-4.90904072e+01]
 [-6.00867979e+02]
 [ 7.38143223e+01]
 [ 8.22291588e+01]
 [-1.02427862e+03]
 [ 1.62677795e+02]
 [ 9.43607419e+00]
 [-1.08975178e+03]
 [ 2.10384891e+02]
 [-3.10881292e+01]
 [-1.09676705e+03]
 [ 8.95770004e-02]
 [-1.40655718e-02]
 [-2.33845412e+00]
 [ 3.75166987e+00]
 [-1.22173154e+01]
 [ 1.38698176e+02]
 [ 1.29259021e+01]
 [-2.52375813e+01]
 [ 2.79455579e+02]
 [ 1.29438700e+01]
 [-2.52279303e+01]
 [ 2.79455543e+02]
 [-5.55082691e+00]
 [-2.4542701